# Generated by Django 3.2.6 on 2021-08-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('documento', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombres y Apellidos')),
                ('contraseña', models.CharField(max_length=15, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Categoria')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('documento', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='No. Cedula')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('direccion_envio', models.CharField(max_length=100, verbose_name='Direccion de envio')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefonono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30, verbose_name='Nombre de prodcto')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmado')], default='P', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comprador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('cod_envio', models.AutoField(primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pedido')),
            ],
        ),
    ]
