# Generated by Django 3.1.13 on 2021-08-11 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_comprador',
            fields=[
                ('documento', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombres y Apellidos')),
                ('contraseña', models.CharField(max_length=15, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripcion de Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='usuario_comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usuario_comprador'),
        ),
    ]
