# Generated by Django 3.1.13 on 2021-08-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210810_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='imagen',
            field=models.CharField(max_length=300, null=True, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(max_length=300, null=True, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='usuario_comprador',
            name='imagen',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
    ]
